/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum Permission {
    GROUND_CONTROL_PROJECT_CREATE = 'ground-control:project:create',
    GROUND_CONTROL_PROJECT_READ_ALL = 'ground-control:project:read_all',
    GROUND_CONTROL_PROJECT_READ = 'ground-control:project:read',
    GROUND_CONTROL_PROJECT_DELETE = 'ground-control:project:delete',
    GROUND_CONTROL_ANNOTATION_CREATE = 'ground-control:annotation:create',
    GROUND_CONTROL_ANNOTATION_GET_ANNOTATIONS_BY_ID = 'ground-control:annotation:get_annotations_by_id',
    GROUND_CONTROL_ANNOTATION_UPDATE_ANNOTATION_RESULT = 'ground-control:annotation:update_annotation_result',
    GROUND_CONTROL_ANNOTATION_FINISH_ANNOTATION = 'ground-control:annotation:finish_annotation',
    GROUND_CONTROL_MEDIA_READ = 'ground-control:media:read',
    GROUND_CONTROL_MEDIA_CREATE = 'ground-control:media:create',
    GROUND_CONTROL_MEDIA_UPDATE = 'ground-control:media:update',
    GROUND_CONTROL_MEDIA_DELETE = 'ground-control:media:delete',
    GROUND_CONTROL_MEDIA_READ_ALL = 'ground-control:media:read_all',
    GROUND_CONTROL_PLUGIN_SEARCH_PLUGINS = 'ground-control:plugin:search_plugins',
    GROUND_CONTROL_PLUGIN_READ_ALL = 'ground-control:plugin:read_all',
    GROUND_CONTROL_PLUGIN_CREATE = 'ground-control:plugin:create',
    GROUND_CONTROL_PLUGIN_DELETE = 'ground-control:plugin:delete',
    GROUND_CONTROL_PLUGIN_READ = 'ground-control:plugin:read',
    GROUND_CONTROL_RESOURCE_GET_TRANSCRIPTION = 'ground-control:resource:get_transcription',
    GROUND_CONTROL_STEP_READ = 'ground-control:step:read',
    GROUND_CONTROL_STEP_CREATE = 'ground-control:step:create',
    GROUND_CONTROL_STEP_UPDATE = 'ground-control:step:update',
    GROUND_CONTROL_STEP_DELETE = 'ground-control:step:delete',
    GROUND_CONTROL_STEP_READ_ALL = 'ground-control:step:read_all',
    GROUND_CONTROL_TAG_READ = 'ground-control:tag:read',
    GROUND_CONTROL_TAG_UPDATE = 'ground-control:tag:update',
    GROUND_CONTROL_TAG_DELETE = 'ground-control:tag:delete',
    GROUND_CONTROL_TAG_READ_ALL = 'ground-control:tag:read_all',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENT = 'ground-control:taskComment:read_task_comment',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENTS_BY_TASK_ID = 'ground-control:taskComment:read_task_comments_by_task_id',
    GROUND_CONTROL_TASK_COMMENT_CREATE_TASK_COMMENT = 'ground-control:taskComment:create_task_comment',
    GROUND_CONTROL_TASK_COMMENT_UPDATE_TASK_COMMENT = 'ground-control:taskComment:update_task_comment',
    GROUND_CONTROL_TASK_COMMENT_DELETE_TASK_COMMENT = 'ground-control:taskComment:delete_task_comment',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENTS = 'ground-control:taskComment:read_task_comments',
    GROUND_CONTROL_TASK_READ = 'ground-control:task:read',
    GROUND_CONTROL_TASK_CREATE = 'ground-control:task:create',
    GROUND_CONTROL_TASK_TASK_INJECT = 'ground-control:task:task_inject',
    GROUND_CONTROL_TASK_UPDATE = 'ground-control:task:update',
    GROUND_CONTROL_USER_READ_ALL = 'ground-control:user:read_all',
    GROUND_CONTROL_USER_CREATE = 'ground-control:user:create',
    GROUND_CONTROL_USER_GET_USER_BY_EMAIL = 'ground-control:user:get_user_by_email',
}
