// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8001' | (string & {});
};

/**
 * AnnotationCreate
 *
 * DTO to create an annotation object
 */
export type AnnotationCreate = {
    /**
     * User Email
     */
    user_email: string;
    annotation_status: Status;
    /**
     * Version
     */
    version: number;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
};

/**
 * AnnotationDto
 *
 * DTO representing an annotation object, including association with task and project.
 */
export type AnnotationDto = {
    /**
     * User Email
     */
    user_email: string;
    annotation_status: Status;
    /**
     * Version
     */
    version: number;
    /**
     * Result
     */
    result: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Validated At
     */
    validated_at: string | null;
};

/**
 * AnnotationFullCreate
 */
export type AnnotationFullCreate = {
    annotation: AnnotationCreate;
    association: AnnotationTaskCreate;
};

/**
 * AnnotationTaskCreate
 *
 * Schema for creating an AnnotationTask, representing the relationship
 * between an annotation and a task.
 *
 * Attributes:
 * -----------
 * annotation_id (int): Identifier of the annotation object.
 * task_id (int): Identifier of the task object.
 * direction (InOutEnum): Describes whether the annotation is input or output.
 */
export type AnnotationTaskCreate = {
    /**
     * Annotation Id
     */
    annotation_id: number;
    /**
     * Task Id
     */
    task_id: number;
    direction: InOutEnum;
};

/**
 * AnnotationType
 *
 * Enum representing the different types of annotations.
 */
export const AnnotationType = {
    SEGMENTATION: 'segmentation',
    TRANSCRIPTION: 'transcription',
    SPAN: 'span',
    AUTO_SUMMARY: 'auto-summary',
    VIDEO_SEGMENTATION: 'video-segmentation'
} as const;

/**
 * AnnotationType
 *
 * Enum representing the different types of annotations.
 */
export type AnnotationType = typeof AnnotationType[keyof typeof AnnotationType];

/**
 * AnnotationWithIdDto
 *
 * DTO base infos + its ID
 */
export type AnnotationWithIdDto = {
    /**
     * User Email
     */
    user_email: string;
    annotation_status: Status;
    /**
     * Version
     */
    version: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Skipped By
     */
    skipped_by: string | null;
};

/**
 * Body_task_inject_step__step_id__post
 */
export type BodyTaskInjectStepStepIdPost = {
    annotation: AnnotationFullCreate;
    task: TaskBaseDto;
    media: MediaCreate;
};

/**
 * ConfigData
 *
 * Configuration data (DTO) for plugin integration.
 *
 * This class defines the core connection and behavior parameters needed by
 * a plugin to interact with its data source.
 *
 * Attributes:
 * type (PluginConfigType): Specifies whether the plugin performs a POST-based
 * search (e.g., ElasticSearch) or a GET-based search (e.g., Wikidata).
 * data_source (str): The endpoint or URL used to query data.
 * data_type (DataTypeEnum): The format of the expected data response.
 * Currently, only 'json' is supported.
 * token_url (str, optional): OAuth2 token endpoint URL, if authentication is required.
 * client_id (str, optional): Client ID for OAuth2 authentication.
 * client_secret (str, optional): Client secret for OAuth2 authentication.
 */
export type ConfigData = {
    type: PluginConfigType;
    /**
     * Data Source
     */
    data_source: string;
    data_type: DataTypeEnum;
    /**
     * Token Url
     */
    token_url?: string | null;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
    [key: string]: unknown | PluginConfigType | string | DataTypeEnum | string | null | string | null | string | null | undefined;
};

/**
 * DataTypeEnum
 */
export const DataTypeEnum = { JSON: 'json' } as const;

/**
 * DataTypeEnum
 */
export type DataTypeEnum = typeof DataTypeEnum[keyof typeof DataTypeEnum];

/**
 * DisplayConfig
 *
 * DTO for plugin display configuration.
 *
 * Attributes:
 * multiple_values (Optional[bool]): Whether multiple values can be selected.
 * max_items (int): Maximum number of items to display.
 * order (int): The display order of the plugin.
 */
export type DisplayConfig = {
    /**
     * Multiple Values
     */
    multiple_values?: boolean | null;
    /**
     * Max Items
     */
    max_items?: number | null;
    /**
     * Order
     */
    order?: number | null;
    /**
     * Main Plugin
     */
    main_plugin?: boolean | null;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Default Value
     */
    default_value?: string | null;
};

/**
 * DisplayZone
 *
 * Enum representing the different display zones available for a plugin.
 *
 * Attributes:
 * BLOC (str): Represents a standalone block zone.
 * SPAN_MODAL_LEFT (str): Represents a modal that spans the left side.
 * SPAN_MODAL_RIGHT (str): Represents a modal that spans the right side.
 * GROUP_MODAL (str): Represents a grouped modal zone for multiple plugins.
 */
export const DisplayZone = {
    BLOC: 'bloc',
    SPAN_MODAL_LEFT: 'span_modal_left',
    SPAN_MODAL_RIGHT: 'span_modal_right',
    GROUP_MODAL: 'group_modal'
} as const;

/**
 * DisplayZone
 *
 * Enum representing the different display zones available for a plugin.
 *
 * Attributes:
 * BLOC (str): Represents a standalone block zone.
 * SPAN_MODAL_LEFT (str): Represents a modal that spans the left side.
 * SPAN_MODAL_RIGHT (str): Represents a modal that spans the right side.
 * GROUP_MODAL (str): Represents a grouped modal zone for multiple plugins.
 */
export type DisplayZone = typeof DisplayZone[keyof typeof DisplayZone];

/**
 * ExceptionResponse
 *
 * Schema used to describe an exception response
 */
export type ExceptionResponse = {
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 *
 * Response model to validate and return when performing a health check.
 */
export type HealthCheck = {
    /**
     * Status
     */
    status?: string;
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Version
     */
    version: string;
};

/**
 * InOutEnum
 *
 * Enum representing the two types of relation between Task and Annotation.
 *
 * Attributes
 * ----------
 * IN (str): The annotation is the initial data of the task,
 * which can either come from an algorithm or a previous annotation.
 * OUT (str): The annotation is the result of the task, containing the user's work.
 */
export const InOutEnum = { IN: 'in', OUT: 'out' } as const;

/**
 * InOutEnum
 *
 * Enum representing the two types of relation between Task and Annotation.
 *
 * Attributes
 * ----------
 * IN (str): The annotation is the initial data of the task,
 * which can either come from an algorithm or a previous annotation.
 * OUT (str): The annotation is the result of the task, containing the user's work.
 */
export type InOutEnum = typeof InOutEnum[keyof typeof InOutEnum];

export type JsonValue = unknown;

/**
 * MediaCreate
 *
 * DTO to create a media object
 */
export type MediaCreate = {
    /**
     * Url
     */
    url: string;
    type: MediaType;
    /**
     * Player Parameters
     */
    player_parameters?: {
        [key: string]: unknown;
    } | PlayerParameters | null;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MediaDto
 *
 * DTO representing a media object, including association with task and project.
 */
export type MediaDto = {
    /**
     * Url
     */
    url: string;
    type: MediaType;
    /**
     * Player Parameters
     */
    player_parameters?: {
        [key: string]: unknown;
    } | PlayerParameters | null;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: number;
    /**
     * Tasks
     */
    tasks: Array<TaskBaseDto> | null;
};

/**
 * MediaType
 *
 * Enum representing the different types a media can have.
 *
 * Attributes:
 * MP4 (str): The media is a mp4 file.
 * HLD (str): The project is a hls file.
 */
export const MediaType = {
    MP4: 'mp4',
    HLS: 'hls',
    MP3: 'mp3'
} as const;

/**
 * MediaType
 *
 * Enum representing the different types a media can have.
 *
 * Attributes:
 * MP4 (str): The media is a mp4 file.
 * HLD (str): The project is a hls file.
 */
export type MediaType = typeof MediaType[keyof typeof MediaType];

/**
 * Permission
 *
 * Represents permission actions as an enumeration for various resources and operations in the system.
 *
 * This class is used to structure and manage permissions related to different
 * resources, such as projects, annotations, media, plugins, steps, tags, tasks, users,
 * and task comments. Each permission is represented as a string value that combines
 * specific elements such as the system name, resource type, and corresponding action.
 *
 * :ivar CREATE_PROJECT: Permission string to create a project.
 * :type CREATE_PROJECT: str
 * :ivar READ_PROJECTS: Permission string to read all projects.
 * :type READ_PROJECTS: str
 * :ivar READ_PROJECT: Permission string to read a single project.
 * :type READ_PROJECT: str
 * :ivar DELETE_PROJECT: Permission string to delete a project.
 * :type DELETE_PROJECT: str
 * :ivar CREATE_ANNOTATION: Permission string to create an annotation.
 * :type CREATE_ANNOTATION: str
 * :ivar GET_ANNOTATIONS_BY_ID: Permission string to get annotations by ID.
 * :type GET_ANNOTATIONS_BY_ID: str
 * :ivar UPDATE_ANNOTATION_RESULT: Permission string to update an annotation result.
 * :type UPDATE_ANNOTATION_RESULT: str
 * :ivar FINISH_ANNOTATION: Permission string to finish an annotation.
 * :type FINISH_ANNOTATION: str
 * :ivar REVIEW_ANNOTATION: Permission string to view someone else's annotation.
 * :type REVIEW_ANNOTATION: str
 * :ivar READ_MEDIA: Permission string to read media.
 * :type READ_MEDIA: str
 * :ivar CREATE_MEDIA: Permission string to create media.
 * :type CREATE_MEDIA: str
 * :ivar UPDATE_DATA_MEDIA: Permission string to update media data.
 * :type UPDATE_DATA_MEDIA: str
 * :ivar DELETE_MEDIA: Permission string to delete media.
 * :type DELETE_MEDIA: str
 * :ivar READ_MEDIAS: Permission string to read all media.
 * :type READ_MEDIAS: str
 * :ivar SEARCH_PLUGINS: Permission string to search plugins.
 * :type SEARCH_PLUGINS: str
 * :ivar READ_PLUGINS: Permission string to read all plugins.
 * :type READ_PLUGINS: str
 * :ivar CREATE_PLUGIN: Permission string to create a plugin.
 * :type CREATE_PLUGIN: str
 * :ivar DELETE_PLUGIN: Permission string to delete a plugin.
 * :type DELETE_PLUGIN: str
 * :ivar READ_PLUGIN: Permission string to read a single plugin.
 * :type READ_PLUGIN: str
 * :ivar GET_TRANSCRIPTION: Permission string to get a transcription.
 * :type GET_TRANSCRIPTION: str
 * :ivar READ_STEP: Permission string to read a step.
 * :type READ_STEP: str
 * :ivar CREATE_STEP: Permission string to create a step.
 * :type CREATE_STEP: str
 * :ivar UPDATE_DATA_STEP: Permission string to update step data.
 * :type UPDATE_DATA_STEP: str
 * :ivar DELETE_STEP: Permission string to delete a step.
 * :type DELETE_STEP: str
 * :ivar READ_STEPS: Permission string to read all steps.
 * :type READ_STEPS: str
 * :ivar READ_TAG: Permission string to read a tag.
 * :type READ_TAG: str
 * :ivar UPDATE_TAG: Permission string to update a tag.
 * :type UPDATE_TAG: str
 * :ivar DELETE_TAG: Permission string to delete a tag.
 * :type DELETE_TAG: str
 * :ivar READ_TAGS: Permission string to read all tags.
 * :type READ_TAGS: str
 * :ivar READ_TASK_COMMENT: Permission string to read a task comment.
 * :type READ_TASK_COMMENT: str
 * :ivar READ_TASK_COMMENTS_BY_TASK_ID: Permission string to read task comments by task ID.
 * :type READ_TASK_COMMENTS_BY_TASK_ID: str
 * :ivar CREATE_TASK_COMMENT: Permission string to create a task comment.
 * :type CREATE_TASK_COMMENT: str
 * :ivar UPDATE_TASK_COMMENT: Permission string to update a task comment.
 * :type UPDATE_TASK_COMMENT: str
 * :ivar DELETE_TASK_COMMENT: Permission string to delete a task comment.
 * :type DELETE_TASK_COMMENT: str
 * :ivar READ_TASK_COMMENTS: Permission string to read all task comments.
 * :type READ_TASK_COMMENTS: str
 * :ivar READ_TASK: Permission string to read a task.
 * :type READ_TASK: str
 * :ivar CREATE_TASK: Permission string to create a task.
 * :type CREATE_TASK: str
 * :ivar TASK_INJECT: Permission string to inject a task.
 * :type TASK_INJECT: str
 * :ivar UPDATE_DATA_TASK: Permission string to update task data.
 * :type UPDATE_DATA_TASK: str
 * :ivar DELETE_TASK: Permission string to delete a task.
 * :type DELETE_TASK: str
 * :ivar READ_USERS: Permission string to read all users.
 * :type READ_USERS: str
 * :ivar CREATE_USER: Permission string to create a user.
 * :type CREATE_USER: str
 * :ivar GET_USER_BY_EMAIL: Permission string to get a user by email.
 * :type GET_USER_BY_EMAIL: str
 */
export const Permission = {
    GROUND_CONTROL_PROJECT_ADMIN: 'ground-control:project:admin',
    GROUND_CONTROL_PROJECT_CREATE: 'ground-control:project:create',
    GROUND_CONTROL_PROJECT_READ_ALL: 'ground-control:project:read_all',
    GROUND_CONTROL_PROJECT_READ: 'ground-control:project:read',
    GROUND_CONTROL_PROJECT_DELETE: 'ground-control:project:delete',
    GROUND_CONTROL_PROJECT_UPDATE: 'ground-control:project:update',
    GROUND_CONTROL_PROJECT_FINISH: 'ground-control:project:finish',
    GROUND_CONTROL_PROJECT_ARCHIVE: 'ground-control:project:archive',
    GROUND_CONTROL_PROJECT_UNARCHIVE: 'ground-control:project:unarchive',
    GROUND_CONTROL_ANNOTATION_CREATE: 'ground-control:annotation:create',
    GROUND_CONTROL_ANNOTATION_GET_ANNOTATIONS_BY_ID: 'ground-control:annotation:get_annotations_by_id',
    GROUND_CONTROL_ANNOTATION_UPDATE_ANNOTATION_RESULT: 'ground-control:annotation:update_annotation_result',
    GROUND_CONTROL_ANNOTATION_FINISH_ANNOTATION: 'ground-control:annotation:finish_annotation',
    GROUND_CONTROL_ANNOTATION_REVIEW: 'ground-control:annotation:review',
    GROUND_CONTROL_MEDIA_READ: 'ground-control:media:read',
    GROUND_CONTROL_MEDIA_CREATE: 'ground-control:media:create',
    GROUND_CONTROL_MEDIA_UPDATE: 'ground-control:media:update',
    GROUND_CONTROL_MEDIA_DELETE: 'ground-control:media:delete',
    GROUND_CONTROL_MEDIA_READ_ALL: 'ground-control:media:read_all',
    GROUND_CONTROL_PLUGIN_SEARCH_PLUGINS: 'ground-control:plugin:search_plugins',
    GROUND_CONTROL_PLUGIN_READ_ALL: 'ground-control:plugin:read_all',
    GROUND_CONTROL_PLUGIN_CREATE: 'ground-control:plugin:create',
    GROUND_CONTROL_PLUGIN_DELETE: 'ground-control:plugin:delete',
    GROUND_CONTROL_PLUGIN_READ: 'ground-control:plugin:read',
    GROUND_CONTROL_RESOURCE_GET_TRANSCRIPTION: 'ground-control:resource:get_transcription',
    GROUND_CONTROL_STEP_READ: 'ground-control:step:read',
    GROUND_CONTROL_STEP_CREATE: 'ground-control:step:create',
    GROUND_CONTROL_STEP_UPDATE: 'ground-control:step:update',
    GROUND_CONTROL_STEP_DELETE: 'ground-control:step:delete',
    GROUND_CONTROL_STEP_READ_ALL: 'ground-control:step:read_all',
    GROUND_CONTROL_TAG_READ: 'ground-control:tag:read',
    GROUND_CONTROL_TAG_UPDATE: 'ground-control:tag:update',
    GROUND_CONTROL_TAG_DELETE: 'ground-control:tag:delete',
    GROUND_CONTROL_TAG_READ_ALL: 'ground-control:tag:read_all',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENT: 'ground-control:taskComment:read_task_comment',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENTS_BY_TASK_ID: 'ground-control:taskComment:read_task_comments_by_task_id',
    GROUND_CONTROL_TASK_COMMENT_CREATE_TASK_COMMENT: 'ground-control:taskComment:create_task_comment',
    GROUND_CONTROL_TASK_COMMENT_UPDATE_TASK_COMMENT: 'ground-control:taskComment:update_task_comment',
    GROUND_CONTROL_TASK_COMMENT_DELETE_TASK_COMMENT: 'ground-control:taskComment:delete_task_comment',
    GROUND_CONTROL_TASK_COMMENT_READ_TASK_COMMENTS: 'ground-control:taskComment:read_task_comments',
    GROUND_CONTROL_TASK_READ: 'ground-control:task:read',
    GROUND_CONTROL_TASK_CREATE: 'ground-control:task:create',
    GROUND_CONTROL_TASK_TASK_INJECT: 'ground-control:task:task_inject',
    GROUND_CONTROL_TASK_UPDATE: 'ground-control:task:update',
    GROUND_CONTROL_TASK_DELETE: 'ground-control:task:delete',
    GROUND_CONTROL_TASK_ACTIVATE: 'ground-control:task:activate',
    GROUND_CONTROL_TASK_UPDATE_EXPIRATION_DATE: 'ground-control:task:update_expiration_date',
    GROUND_CONTROL_USER_READ_ALL: 'ground-control:user:read_all',
    GROUND_CONTROL_USER_CREATE: 'ground-control:user:create',
    GROUND_CONTROL_USER_GET_USER_BY_EMAIL: 'ground-control:user:get_user_by_email'
} as const;

/**
 * Permission
 *
 * Represents permission actions as an enumeration for various resources and operations in the system.
 *
 * This class is used to structure and manage permissions related to different
 * resources, such as projects, annotations, media, plugins, steps, tags, tasks, users,
 * and task comments. Each permission is represented as a string value that combines
 * specific elements such as the system name, resource type, and corresponding action.
 *
 * :ivar CREATE_PROJECT: Permission string to create a project.
 * :type CREATE_PROJECT: str
 * :ivar READ_PROJECTS: Permission string to read all projects.
 * :type READ_PROJECTS: str
 * :ivar READ_PROJECT: Permission string to read a single project.
 * :type READ_PROJECT: str
 * :ivar DELETE_PROJECT: Permission string to delete a project.
 * :type DELETE_PROJECT: str
 * :ivar CREATE_ANNOTATION: Permission string to create an annotation.
 * :type CREATE_ANNOTATION: str
 * :ivar GET_ANNOTATIONS_BY_ID: Permission string to get annotations by ID.
 * :type GET_ANNOTATIONS_BY_ID: str
 * :ivar UPDATE_ANNOTATION_RESULT: Permission string to update an annotation result.
 * :type UPDATE_ANNOTATION_RESULT: str
 * :ivar FINISH_ANNOTATION: Permission string to finish an annotation.
 * :type FINISH_ANNOTATION: str
 * :ivar REVIEW_ANNOTATION: Permission string to view someone else's annotation.
 * :type REVIEW_ANNOTATION: str
 * :ivar READ_MEDIA: Permission string to read media.
 * :type READ_MEDIA: str
 * :ivar CREATE_MEDIA: Permission string to create media.
 * :type CREATE_MEDIA: str
 * :ivar UPDATE_DATA_MEDIA: Permission string to update media data.
 * :type UPDATE_DATA_MEDIA: str
 * :ivar DELETE_MEDIA: Permission string to delete media.
 * :type DELETE_MEDIA: str
 * :ivar READ_MEDIAS: Permission string to read all media.
 * :type READ_MEDIAS: str
 * :ivar SEARCH_PLUGINS: Permission string to search plugins.
 * :type SEARCH_PLUGINS: str
 * :ivar READ_PLUGINS: Permission string to read all plugins.
 * :type READ_PLUGINS: str
 * :ivar CREATE_PLUGIN: Permission string to create a plugin.
 * :type CREATE_PLUGIN: str
 * :ivar DELETE_PLUGIN: Permission string to delete a plugin.
 * :type DELETE_PLUGIN: str
 * :ivar READ_PLUGIN: Permission string to read a single plugin.
 * :type READ_PLUGIN: str
 * :ivar GET_TRANSCRIPTION: Permission string to get a transcription.
 * :type GET_TRANSCRIPTION: str
 * :ivar READ_STEP: Permission string to read a step.
 * :type READ_STEP: str
 * :ivar CREATE_STEP: Permission string to create a step.
 * :type CREATE_STEP: str
 * :ivar UPDATE_DATA_STEP: Permission string to update step data.
 * :type UPDATE_DATA_STEP: str
 * :ivar DELETE_STEP: Permission string to delete a step.
 * :type DELETE_STEP: str
 * :ivar READ_STEPS: Permission string to read all steps.
 * :type READ_STEPS: str
 * :ivar READ_TAG: Permission string to read a tag.
 * :type READ_TAG: str
 * :ivar UPDATE_TAG: Permission string to update a tag.
 * :type UPDATE_TAG: str
 * :ivar DELETE_TAG: Permission string to delete a tag.
 * :type DELETE_TAG: str
 * :ivar READ_TAGS: Permission string to read all tags.
 * :type READ_TAGS: str
 * :ivar READ_TASK_COMMENT: Permission string to read a task comment.
 * :type READ_TASK_COMMENT: str
 * :ivar READ_TASK_COMMENTS_BY_TASK_ID: Permission string to read task comments by task ID.
 * :type READ_TASK_COMMENTS_BY_TASK_ID: str
 * :ivar CREATE_TASK_COMMENT: Permission string to create a task comment.
 * :type CREATE_TASK_COMMENT: str
 * :ivar UPDATE_TASK_COMMENT: Permission string to update a task comment.
 * :type UPDATE_TASK_COMMENT: str
 * :ivar DELETE_TASK_COMMENT: Permission string to delete a task comment.
 * :type DELETE_TASK_COMMENT: str
 * :ivar READ_TASK_COMMENTS: Permission string to read all task comments.
 * :type READ_TASK_COMMENTS: str
 * :ivar READ_TASK: Permission string to read a task.
 * :type READ_TASK: str
 * :ivar CREATE_TASK: Permission string to create a task.
 * :type CREATE_TASK: str
 * :ivar TASK_INJECT: Permission string to inject a task.
 * :type TASK_INJECT: str
 * :ivar UPDATE_DATA_TASK: Permission string to update task data.
 * :type UPDATE_DATA_TASK: str
 * :ivar DELETE_TASK: Permission string to delete a task.
 * :type DELETE_TASK: str
 * :ivar READ_USERS: Permission string to read all users.
 * :type READ_USERS: str
 * :ivar CREATE_USER: Permission string to create a user.
 * :type CREATE_USER: str
 * :ivar GET_USER_BY_EMAIL: Permission string to get a user by email.
 * :type GET_USER_BY_EMAIL: str
 */
export type Permission = typeof Permission[keyof typeof Permission];

/**
 * PlayerParameters
 *
 * DTO for the configuration data of a player_parameters.
 */
export type PlayerParameters = {
    /**
     * Thumbnail Base Url
     */
    thumbnail_base_url?: string;
    /**
     * Download Base Url
     */
    download_base_url?: string;
    /**
     * Waveform Base Url
     */
    waveform_base_url?: string;
    /**
     * Tc Offset
     */
    tc_offset?: number;
    /**
     * Headers
     */
    headers?: {
        [key: string]: string;
    };
    [key: string]: unknown | string | number | {
        [key: string]: string;
    } | undefined;
};

/**
 * PluginAutocompleteValueDTO
 *
 * Data Transfer Object representing a plugin autocomplete value.
 *
 * Attributes:
 * id (Optional[str | int]): Internal identifier.
 * ext_id (Optional[str]): External identifier.
 * label (Optional[str]): Display label.
 * tag_label (Optional[str]): Alternative label used for tagging.
 * link (Optional[str]): External URL associated with the value.
 * image (Optional[str]): URL of the image displayed next to the option.
 * description (Optional[str]): Additional descriptive information.
 * categories (Optional[str]): Stringified JSON array of categories.
 * group (Optional[str]): Group name for visual grouping in UI.
 * editable (Optional[str]): Indicates if the value is editable.
 * copyable (Optional[str]): Indicates if the value is copyable.
 * tooltip (Optional[str]): Tooltip text displayed in UI.
 */
export type PluginAutocompleteValueDto = {
    /**
     * Id
     */
    id?: string | number | null;
    /**
     * Ext Id
     */
    ext_id?: string | null;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Tag Label
     */
    tag_label?: string | null;
    /**
     * Link
     */
    link?: string | null;
    /**
     * Image
     */
    image?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Categories
     */
    categories?: string | null;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Editable
     */
    editable?: string | null;
    /**
     * Copyable
     */
    copyable?: string | null;
    /**
     * Tooltip
     */
    tooltip?: string | null;
};

/**
 * PluginConfigType
 */
export const PluginConfigType = {
    PLUGIN_REQUEST_POST: 'plugin_request_post',
    PLUGIN_REQUEST_GET: 'plugin_request_get',
    PLUGIN_WIKIDATA: 'plugin_wikidata',
    PLUGIN_STATIC_DATA: 'plugin_static_data'
} as const;

/**
 * PluginConfigType
 */
export type PluginConfigType = typeof PluginConfigType[keyof typeof PluginConfigType];

/**
 * PluginCreate
 *
 * DTO to create a plugin object.
 *
 * Attributes:
 * name (str): The name of the plugin.
 * type (TypePlugin): The type of the plugin (from `TypePlugin` enum).
 * data_categories (str): Categories for the plugin's data.
 * display_zone (DisplayZone): The display zone for the plugin.
 * step_id (int): The ID of the step associated with the plugin.
 * config_data (ConfigData): Configuration data for the plugin.
 * display_config (Optional[DisplayConfig]): Optional display configuration.
 * enable_search (Optional[bool]): Enable search feature for embedded plugins.
 * data_property (Optional[str]): Data property reference for embedded plugins.
 * children_plugins (Optional[List[PluginCreate]]): List of embedded child plugins.
 */
export type PluginCreate = {
    /**
     * Name
     */
    name: string;
    type: TypePlugin;
    /**
     * Data Categories
     */
    data_categories: string;
    display_zone: DisplayZone;
    /**
     * Step Id
     */
    step_id: number;
    available_plugins?: JsonValue | null;
    config_data: ConfigData;
    display_config?: DisplayConfig | null;
    /**
     * Enable Search
     */
    enable_search?: boolean | null;
    /**
     * Data Property
     */
    data_property?: string | null;
    /**
     * Children
     */
    children?: Array<PluginCreate> | null;
};

/**
 * PluginWithIdDto
 *
 * Extends PluginCreate with an additional id field.
 *
 * Attributes:
 * id (int): The unique identifier of the plugin.
 */
export type PluginWithIdDto = {
    /**
     * Name
     */
    name: string;
    type: TypePlugin;
    /**
     * Data Categories
     */
    data_categories: string;
    display_zone: DisplayZone;
    /**
     * Step Id
     */
    step_id: number;
    available_plugins?: JsonValue | null;
    config_data: ConfigData;
    display_config?: DisplayConfig | null;
    /**
     * Enable Search
     */
    enable_search?: boolean | null;
    /**
     * Data Property
     */
    data_property?: string | null;
    /**
     * Children
     */
    children?: Array<PluginWithIdDto> | null;
    /**
     * Id
     */
    id: number;
};

/**
 * ProjectBaseDto
 *
 * Base DTO for project objects.
 */
export type ProjectBaseDto = {
    /**
     * Title
     */
    title: string | null;
    /**
     * Description
     */
    description: string | null;
    status: Status | null;
    /**
     * Is Published
     */
    is_published: boolean | null;
    /**
     * Empty Annotations
     */
    empty_annotations: boolean | null;
    /**
     * Allow Skip
     */
    allow_skip: boolean | null;
    /**
     * Control Weights
     */
    control_weights: number | null;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    /**
     * Created By
     */
    created_by: string;
};

/**
 * ProjectDetailDto
 *
 * Detailed DTO for project objects, including creation and update timestamps,
 * a list of tasks, and counts of users with annotations and total tasks.
 *
 * Used in `/dashboard` view
 */
export type ProjectDetailDto = {
    /**
     * Title
     */
    title: string | null;
    /**
     * Description
     */
    description: string | null;
    status: Status | null;
    /**
     * Is Published
     */
    is_published: boolean | null;
    /**
     * Empty Annotations
     */
    empty_annotations: boolean | null;
    /**
     * Allow Skip
     */
    allow_skip: boolean | null;
    /**
     * Control Weights
     */
    control_weights: number | null;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Steps
     */
    steps: Array<StepDto>;
    /**
     * Medias
     */
    medias: Array<MediaCreate>;
};

/**
 * ProjectListDto
 *
 * DTO for listing projects, including a list of tasks.
 *
 * Used in `/{project_id}` view
 */
export type ProjectListDto = {
    /**
     * Title
     */
    title: string | null;
    /**
     * Description
     */
    description: string | null;
    status: Status | null;
    /**
     * Is Published
     */
    is_published: boolean | null;
    /**
     * Empty Annotations
     */
    empty_annotations: boolean | null;
    /**
     * Allow Skip
     */
    allow_skip: boolean | null;
    /**
     * Control Weights
     */
    control_weights: number | null;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Medias
     */
    medias: Array<MediaCreate>;
    /**
     * Steps
     */
    steps?: Array<StepDetailDto> | null;
    /**
     * Tasks To Annotate
     */
    tasks_to_annotate?: Array<TaskWithIdDto> | null;
};

/**
 * ProjectListDtoSummary
 */
export type ProjectListDtoSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Steps Count
     */
    steps_count: number;
    status: Status | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Tasks Id To Annotate
     */
    tasks_id_to_annotate?: Array<number> | null;
};

/**
 * ProjectParametersResponse
 */
export type ProjectParametersResponse = {
    /**
     * Redundancy
     */
    redundancy: number;
    /**
     * Completeness Rate
     */
    completeness_rate: number;
    /**
     * Allow Empty Annotation
     */
    allow_empty_annotation: boolean;
    /**
     * Max Tasks Per Person
     */
    max_tasks_per_person: number;
    /**
     * Allow Skip
     */
    allow_skip: boolean;
};

/**
 * ProjectWithIdDto
 *
 * Extends ProjectBaseDto with an additional id field.
 */
export type ProjectWithIdDto = {
    /**
     * Title
     */
    title: string | null;
    /**
     * Description
     */
    description: string | null;
    status: Status | null;
    /**
     * Is Published
     */
    is_published: boolean | null;
    /**
     * Empty Annotations
     */
    empty_annotations: boolean | null;
    /**
     * Allow Skip
     */
    allow_skip: boolean | null;
    /**
     * Control Weights
     */
    control_weights: number | null;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: number;
};

/**
 * Status
 *
 * Enum representing the different statuses an annotation, task, step, and project can have.
 */
export const Status = {
    DRAFT: 'draft',
    IN_PROGRESS: 'in-progress',
    PENDING: 'pending',
    SKIPPED: 'skipped',
    DONE: 'done',
    ARCHIVED: 'archived'
} as const;

/**
 * Status
 *
 * Enum representing the different statuses an annotation, task, step, and project can have.
 */
export type Status = typeof Status[keyof typeof Status];

/**
 * StepCreate
 *
 * DTO to create a step object
 */
export type StepCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    annotation_type: AnnotationType;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    status: Status;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Redundancy
     *
     * Number of annotations per task
     */
    redundancy?: number;
    /**
     * Completeness Rate
     *
     * Must be between 0 and 100
     */
    completeness_rate?: number;
    /**
     * Allow Empty Annotation
     *
     * Allow empty annotations
     */
    allow_empty_annotation?: boolean;
    /**
     * Max Tasks Per Person
     *
     * Must be at least 1
     */
    max_tasks_per_person?: number;
};

/**
 * StepDetailDto
 *
 * DTO representing the step object with its related tasks objects.
 *
 * Used in `/{project_id}` view
 */
export type StepDetailDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    annotation_type: AnnotationType;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    status: Status;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Redundancy
     *
     * Number of annotations per task
     */
    redundancy?: number;
    /**
     * Completeness Rate
     *
     * Must be between 0 and 100
     */
    completeness_rate?: number;
    /**
     * Allow Empty Annotation
     *
     * Allow empty annotations
     */
    allow_empty_annotation?: boolean;
    /**
     * Max Tasks Per Person
     *
     * Must be at least 1
     */
    max_tasks_per_person?: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Tasks
     */
    tasks: Array<TaskWithIdDto> | null;
    /**
     * Plugins
     */
    plugins: Array<PluginWithIdDto> | null;
};

/**
 * StepDto
 *
 * DTO representing a step object, including association with task and project.
 */
export type StepDto = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    annotation_type: AnnotationType;
    /**
     * Pinned At
     */
    pinned_at: string | null;
    status: Status;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Redundancy
     *
     * Number of annotations per task
     */
    redundancy?: number;
    /**
     * Completeness Rate
     *
     * Must be between 0 and 100
     */
    completeness_rate?: number;
    /**
     * Allow Empty Annotation
     *
     * Allow empty annotations
     */
    allow_empty_annotation?: boolean;
    /**
     * Max Tasks Per Person
     *
     * Must be at least 1
     */
    max_tasks_per_person?: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
};

/**
 * StepProjectDto
 */
export type StepProjectDto = {
    annotation_type: AnnotationType;
    project: ProjectWithIdDto;
};

/**
 * TagCreate
 *
 * DTO to create a tag object
 */
export type TagCreate = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * TagDto
 *
 * DTO representing a tag object, including association with projectls.
 */
export type TagDto = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
    /**
     * Project Id
     */
    project_id: number;
};

/**
 * TaskBaseDto
 *
 * Base DTO for task objects.
 */
export type TaskBaseDto = {
    /**
     * Name
     */
    name: string;
    /**
     * Instruction
     */
    instruction?: string | null;
    data_type: TaskDataType;
    status: Status;
    previous_status?: Status | null;
    /**
     * Lead Time
     */
    lead_time: number | null;
    /**
     * Step Id
     */
    step_id: number;
    /**
     * Media Id
     */
    media_id: number;
    /**
     * Documentation
     */
    documentation?: string | null;
    /**
     * Expiration Date
     */
    expiration_date?: string | null;
    /**
     * Redundancy
     */
    redundancy?: number;
    /**
     * Priority
     */
    priority?: number;
};

/**
 * TaskCommentCreate
 *
 * DTO to create a taskComment object
 */
export type TaskCommentCreate = {
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Created By
     */
    created_by: string;
};

/**
 * TaskCommentDto
 *
 * DTO representing a taskComment object, including association with task.
 */
export type TaskCommentDto = {
    /**
     * Comment
     */
    comment: string | null;
    /**
     * Task Id
     */
    task_id: number;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * TaskDataType
 *
 * Enum representing the different datatypes of tasks.
 *
 * Attributes:
 * LDD (str): The annotation type for ldd tasks.
 * AMALIA (str): The annotation type for amalia tasks.
 */
export const TaskDataType = { LDD: 'ldd', AMALIA: 'amalia' } as const;

/**
 * TaskDataType
 *
 * Enum representing the different datatypes of tasks.
 *
 * Attributes:
 * LDD (str): The annotation type for ldd tasks.
 * AMALIA (str): The annotation type for amalia tasks.
 */
export type TaskDataType = typeof TaskDataType[keyof typeof TaskDataType];

/**
 * TaskListDto
 *
 * DTO for listing tasks, extending TaskCreateDto with additional
 * fields relevant for listing tasks.
 */
export type TaskListDto = {
    /**
     * Name
     */
    name: string;
    /**
     * Instruction
     */
    instruction?: string | null;
    data_type: TaskDataType;
    status: Status;
    previous_status?: Status | null;
    /**
     * Lead Time
     */
    lead_time: number | null;
    /**
     * Step Id
     */
    step_id: number;
    /**
     * Media Id
     */
    media_id: number;
    /**
     * Documentation
     */
    documentation?: string | null;
    /**
     * Expiration Date
     */
    expiration_date?: string | null;
    /**
     * Redundancy
     */
    redundancy?: number;
    /**
     * Priority
     */
    priority?: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Task Comments
     */
    task_comments?: Array<TaskCommentDto>;
    step: StepProjectDto | null;
    media: MediaDto | null;
    /**
     * Annotations
     */
    annotations: Array<AnnotationWithIdDto>;
};

/**
 * TaskWithIdDto
 *
 * Extends TaskBaseDto with an additional id field.
 */
export type TaskWithIdDto = {
    /**
     * Name
     */
    name: string;
    /**
     * Instruction
     */
    instruction?: string | null;
    data_type: TaskDataType;
    status: Status;
    previous_status?: Status | null;
    /**
     * Lead Time
     */
    lead_time: number | null;
    /**
     * Step Id
     */
    step_id: number;
    /**
     * Media Id
     */
    media_id: number;
    /**
     * Documentation
     */
    documentation?: string | null;
    /**
     * Expiration Date
     */
    expiration_date?: string | null;
    /**
     * Redundancy
     */
    redundancy?: number;
    /**
     * Priority
     */
    priority?: number;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string | null;
    /**
     * Annotations
     */
    annotations?: Array<AnnotationWithIdDto>;
};

/**
 * TypePlugin
 *
 *     Enum representing the different plugin types.
 *
 * Values:
 * LABEL: Label plugin
 * AUTOCOMPLETE: List with autocomplete functionality.
 * LIST_ITEMS: Displays tags and list of items.
 * SUGGESTION_LIST: Interactive suggestion block.
 * .       INPUT_LABEL: Simple text input field.
 */
export const TypePlugin = {
    LABEL: 'label',
    AUTOCOMPLETE: 'autocomplete',
    LISTITEMS: 'listitems',
    SUGGESTIONLIST: 'suggestionlist',
    INPUTLABEL: 'inputlabel'
} as const;

/**
 * TypePlugin
 *
 *     Enum representing the different plugin types.
 *
 * Values:
 * LABEL: Label plugin
 * AUTOCOMPLETE: List with autocomplete functionality.
 * LIST_ITEMS: Displays tags and list of items.
 * SUGGESTION_LIST: Interactive suggestion block.
 * .       INPUT_LABEL: Simple text input field.
 */
export type TypePlugin = typeof TypePlugin[keyof typeof TypePlugin];

/**
 * UserBaseDto
 *
 * Base DTO representing a user object.
 */
export type UserBaseDto = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
};

/**
 * UserDto
 *
 * DTO representing a user object, extending UserBaseDto with associated projects.
 */
export type UserDto = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
    /**
     * Projects
     */
    projects?: Array<ProjectDetailDto>;
    /**
     * Annotations
     */
    annotations?: Array<AnnotationCreate>;
    /**
     * Created At
     */
    created_at: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/users';
};

export type ReadUsersUsersGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersUsersGetError = ReadUsersUsersGetErrors[keyof ReadUsersUsersGetErrors];

export type ReadUsersUsersGetResponses = {
    /**
     * Response Read Users Users Get
     *
     * Successful Response
     */
    200: Array<UserDto>;
};

export type ReadUsersUsersGetResponse = ReadUsersUsersGetResponses[keyof ReadUsersUsersGetResponses];

export type CreateUserUserPostData = {
    body: UserBaseDto;
    path?: never;
    query?: never;
    url: '/user';
};

export type CreateUserUserPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUserPostError = CreateUserUserPostErrors[keyof CreateUserUserPostErrors];

export type CreateUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: UserDto;
};

export type CreateUserUserPostResponse = CreateUserUserPostResponses[keyof CreateUserUserPostResponses];

export type GetAllRolesUserRolesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/roles';
};

export type GetAllRolesUserRolesGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
};

export type GetAllRolesUserRolesGetError = GetAllRolesUserRolesGetErrors[keyof GetAllRolesUserRolesGetErrors];

export type GetAllRolesUserRolesGetResponses = {
    /**
     * Successful Response
     */
    200: Permission;
};

export type GetAllRolesUserRolesGetResponse = GetAllRolesUserRolesGetResponses[keyof GetAllRolesUserRolesGetResponses];

export type GetUserByEmailUserGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/user/';
};

export type GetUserByEmailUserGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByEmailUserGetError = GetUserByEmailUserGetErrors[keyof GetUserByEmailUserGetErrors];

export type GetUserByEmailUserGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/projects';
};

export type ReadProjectsProjectsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectsProjectsGetError = ReadProjectsProjectsGetErrors[keyof ReadProjectsProjectsGetErrors];

export type ReadProjectsProjectsGetResponses = {
    /**
     * Response Read Projects Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectListDto>;
};

export type ReadProjectsProjectsGetResponse = ReadProjectsProjectsGetResponses[keyof ReadProjectsProjectsGetResponses];

export type ReadProjectsSummaryProjectsSummaryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/projects/summary';
};

export type ReadProjectsSummaryProjectsSummaryGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectsSummaryProjectsSummaryGetError = ReadProjectsSummaryProjectsSummaryGetErrors[keyof ReadProjectsSummaryProjectsSummaryGetErrors];

export type ReadProjectsSummaryProjectsSummaryGetResponses = {
    /**
     * Response Read Projects Summary Projects Summary Get
     *
     * Successful Response
     */
    200: Array<ProjectListDtoSummary>;
};

export type ReadProjectsSummaryProjectsSummaryGetResponse = ReadProjectsSummaryProjectsSummaryGetResponses[keyof ReadProjectsSummaryProjectsSummaryGetResponses];

export type CreateProjectProjectPostData = {
    body: ProjectBaseDto;
    path?: never;
    query?: never;
    url: '/project';
};

export type CreateProjectProjectPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectProjectPostError = CreateProjectProjectPostErrors[keyof CreateProjectProjectPostErrors];

export type CreateProjectProjectPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectDetailDto;
};

export type CreateProjectProjectPostResponse = CreateProjectProjectPostResponses[keyof CreateProjectProjectPostResponses];

export type ReadProjectBasicProjectProjectIdBasicGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/project/{project_id}/basic';
};

export type ReadProjectBasicProjectProjectIdBasicGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectBasicProjectProjectIdBasicGetError = ReadProjectBasicProjectProjectIdBasicGetErrors[keyof ReadProjectBasicProjectProjectIdBasicGetErrors];

export type ReadProjectBasicProjectProjectIdBasicGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectListDto;
};

export type ReadProjectBasicProjectProjectIdBasicGetResponse = ReadProjectBasicProjectProjectIdBasicGetResponses[keyof ReadProjectBasicProjectProjectIdBasicGetResponses];

export type DeleteProjectProjectProjectIdDeleteData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/project/{project_id}';
};

export type DeleteProjectProjectProjectIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectProjectProjectIdDeleteError = DeleteProjectProjectProjectIdDeleteErrors[keyof DeleteProjectProjectProjectIdDeleteErrors];

export type DeleteProjectProjectProjectIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: ProjectWithIdDto;
};

export type DeleteProjectProjectProjectIdDeleteResponse = DeleteProjectProjectProjectIdDeleteResponses[keyof DeleteProjectProjectProjectIdDeleteResponses];

export type ReadProjectProjectProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/project/{project_id}';
};

export type ReadProjectProjectProjectIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectProjectProjectIdGetError = ReadProjectProjectProjectIdGetErrors[keyof ReadProjectProjectProjectIdGetErrors];

export type ReadProjectProjectProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectListDto;
};

export type ReadProjectProjectProjectIdGetResponse = ReadProjectProjectProjectIdGetResponses[keyof ReadProjectProjectProjectIdGetResponses];

export type UpdateProjectProjectProjectIdPutData = {
    body: ProjectBaseDto;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/project/{project_id}';
};

export type UpdateProjectProjectProjectIdPutErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectProjectProjectIdPutError = UpdateProjectProjectProjectIdPutErrors[keyof UpdateProjectProjectProjectIdPutErrors];

export type UpdateProjectProjectProjectIdPutResponses = {
    /**
     * Successful Response
     */
    200: ProjectWithIdDto;
};

export type UpdateProjectProjectProjectIdPutResponse = UpdateProjectProjectProjectIdPutResponses[keyof UpdateProjectProjectProjectIdPutResponses];

export type ReadProjectParametersProjectIdParametersGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/{project_id}/parameters';
};

export type ReadProjectParametersProjectIdParametersGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectParametersProjectIdParametersGetError = ReadProjectParametersProjectIdParametersGetErrors[keyof ReadProjectParametersProjectIdParametersGetErrors];

export type ReadProjectParametersProjectIdParametersGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectParametersResponse;
};

export type ReadProjectParametersProjectIdParametersGetResponse = ReadProjectParametersProjectIdParametersGetResponses[keyof ReadProjectParametersProjectIdParametersGetResponses];

export type FinishProjectProjectIdFinishPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/{project_id}/finish';
};

export type FinishProjectProjectIdFinishPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishProjectProjectIdFinishPostError = FinishProjectProjectIdFinishPostErrors[keyof FinishProjectProjectIdFinishPostErrors];

export type FinishProjectProjectIdFinishPostResponses = {
    /**
     * Successful Response
     */
    200: ProjectWithIdDto;
};

export type FinishProjectProjectIdFinishPostResponse = FinishProjectProjectIdFinishPostResponses[keyof FinishProjectProjectIdFinishPostResponses];

export type GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/{project_id}/progressed_tasks/count';
};

export type GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostError = GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostErrors[keyof GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostErrors];

export type GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostResponses = {
    /**
     * Response Get Progressed Tasks Count For Project  Project Id  Progressed Tasks Count Post
     *
     * Successful Response
     */
    200: number;
};

export type GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostResponse = GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostResponses[keyof GetProgressedTasksCountForProjectProjectIdProgressedTasksCountPostResponses];

export type ArchiveProjectProjectIdArchivePostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/{project_id}/archive';
};

export type ArchiveProjectProjectIdArchivePostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveProjectProjectIdArchivePostError = ArchiveProjectProjectIdArchivePostErrors[keyof ArchiveProjectProjectIdArchivePostErrors];

export type ArchiveProjectProjectIdArchivePostResponses = {
    /**
     * Successful Response
     */
    200: ProjectWithIdDto;
};

export type ArchiveProjectProjectIdArchivePostResponse = ArchiveProjectProjectIdArchivePostResponses[keyof ArchiveProjectProjectIdArchivePostResponses];

export type UnarchiveProjectProjectIdUnarchivePostData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: number;
    };
    query?: never;
    url: '/{project_id}/unarchive';
};

export type UnarchiveProjectProjectIdUnarchivePostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnarchiveProjectProjectIdUnarchivePostError = UnarchiveProjectProjectIdUnarchivePostErrors[keyof UnarchiveProjectProjectIdUnarchivePostErrors];

export type UnarchiveProjectProjectIdUnarchivePostResponses = {
    /**
     * Successful Response
     */
    200: ProjectWithIdDto;
};

export type UnarchiveProjectProjectIdUnarchivePostResponse = UnarchiveProjectProjectIdUnarchivePostResponses[keyof UnarchiveProjectProjectIdUnarchivePostResponses];

export type DeleteTaskTaskTaskIdDeleteData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/task/{task_id}';
};

export type DeleteTaskTaskTaskIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskTaskTaskIdDeleteError = DeleteTaskTaskTaskIdDeleteErrors[keyof DeleteTaskTaskTaskIdDeleteErrors];

export type DeleteTaskTaskTaskIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: TaskWithIdDto;
};

export type DeleteTaskTaskTaskIdDeleteResponse = DeleteTaskTaskTaskIdDeleteResponses[keyof DeleteTaskTaskTaskIdDeleteResponses];

export type ReadTaskTaskTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/task/{task_id}';
};

export type ReadTaskTaskTaskIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskTaskTaskIdGetError = ReadTaskTaskTaskIdGetErrors[keyof ReadTaskTaskTaskIdGetErrors];

export type ReadTaskTaskTaskIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskListDto;
};

export type ReadTaskTaskTaskIdGetResponse = ReadTaskTaskTaskIdGetResponses[keyof ReadTaskTaskTaskIdGetResponses];

export type UpdateDataTaskTaskTaskIdPatchData = {
    /**
     * Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: never;
    url: '/task/{task_id}';
};

export type UpdateDataTaskTaskTaskIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDataTaskTaskTaskIdPatchError = UpdateDataTaskTaskTaskIdPatchErrors[keyof UpdateDataTaskTaskTaskIdPatchErrors];

export type UpdateDataTaskTaskTaskIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TaskListDto;
};

export type UpdateDataTaskTaskTaskIdPatchResponse = UpdateDataTaskTaskTaskIdPatchResponses[keyof UpdateDataTaskTaskTaskIdPatchResponses];

export type CreateTaskTaskPostData = {
    body: TaskBaseDto;
    path?: never;
    query?: never;
    url: '/task';
};

export type CreateTaskTaskPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskTaskPostError = CreateTaskTaskPostErrors[keyof CreateTaskTaskPostErrors];

export type CreateTaskTaskPostResponses = {
    /**
     * Successful Response
     */
    200: TaskWithIdDto;
};

export type CreateTaskTaskPostResponse = CreateTaskTaskPostResponses[keyof CreateTaskTaskPostResponses];

export type DeleteStepStepStepIdDeleteData = {
    body?: never;
    path: {
        /**
         * Step Id
         */
        step_id: number;
    };
    query?: never;
    url: '/step/{step_id}';
};

export type DeleteStepStepStepIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteStepStepStepIdDeleteError = DeleteStepStepStepIdDeleteErrors[keyof DeleteStepStepStepIdDeleteErrors];

export type DeleteStepStepStepIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: StepCreate;
};

export type DeleteStepStepStepIdDeleteResponse = DeleteStepStepStepIdDeleteResponses[keyof DeleteStepStepStepIdDeleteResponses];

export type ReadStepStepStepIdGetData = {
    body?: never;
    path: {
        /**
         * Step Id
         */
        step_id: number;
    };
    query?: never;
    url: '/step/{step_id}';
};

export type ReadStepStepStepIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStepStepStepIdGetError = ReadStepStepStepIdGetErrors[keyof ReadStepStepStepIdGetErrors];

export type ReadStepStepStepIdGetResponses = {
    /**
     * Successful Response
     */
    200: StepDto;
};

export type ReadStepStepStepIdGetResponse = ReadStepStepStepIdGetResponses[keyof ReadStepStepStepIdGetResponses];

export type UpdateDataStepStepStepIdPatchData = {
    body: StepCreate;
    path: {
        /**
         * Step Id
         */
        step_id: number;
    };
    query?: never;
    url: '/step/{step_id}';
};

export type UpdateDataStepStepStepIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDataStepStepStepIdPatchError = UpdateDataStepStepStepIdPatchErrors[keyof UpdateDataStepStepStepIdPatchErrors];

export type UpdateDataStepStepStepIdPatchResponses = {
    /**
     * Successful Response
     */
    200: StepDto;
};

export type UpdateDataStepStepStepIdPatchResponse = UpdateDataStepStepStepIdPatchResponses[keyof UpdateDataStepStepStepIdPatchResponses];

export type TaskInjectStepStepIdPostData = {
    body: BodyTaskInjectStepStepIdPost;
    path: {
        /**
         * Step Id
         */
        step_id: number;
    };
    query?: {
        /**
         * Activate
         *
         * Whether to activate the task
         */
        activate?: boolean;
    };
    url: '/step/{step_id}';
};

export type TaskInjectStepStepIdPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TaskInjectStepStepIdPostError = TaskInjectStepStepIdPostErrors[keyof TaskInjectStepStepIdPostErrors];

export type TaskInjectStepStepIdPostResponses = {
    /**
     * Successful Response
     */
    200: TaskWithIdDto;
};

export type TaskInjectStepStepIdPostResponse = TaskInjectStepStepIdPostResponses[keyof TaskInjectStepStepIdPostResponses];

export type UpdateTaskStatusTaskTaskIdStatusPostData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query: {
        status: Status;
    };
    url: '/task/{task_id}/status';
};

export type UpdateTaskStatusTaskTaskIdStatusPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskStatusTaskTaskIdStatusPostError = UpdateTaskStatusTaskTaskIdStatusPostErrors[keyof UpdateTaskStatusTaskTaskIdStatusPostErrors];

export type UpdateTaskStatusTaskTaskIdStatusPostResponses = {
    /**
     * Successful Response
     */
    200: TaskListDto;
};

export type UpdateTaskStatusTaskTaskIdStatusPostResponse = UpdateTaskStatusTaskTaskIdStatusPostResponses[keyof UpdateTaskStatusTaskTaskIdStatusPostResponses];

export type UpdateTasksStatusTasksStatusPostData = {
    /**
     * Tasks Id
     */
    body: Array<number>;
    path?: never;
    query: {
        status: Status;
    };
    url: '/tasks/status';
};

export type UpdateTasksStatusTasksStatusPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTasksStatusTasksStatusPostError = UpdateTasksStatusTasksStatusPostErrors[keyof UpdateTasksStatusTasksStatusPostErrors];

export type UpdateTasksStatusTasksStatusPostResponses = {
    /**
     * Response Update Tasks Status Tasks Status Post
     *
     * Successful Response
     */
    200: Array<number>;
};

export type UpdateTasksStatusTasksStatusPostResponse = UpdateTasksStatusTasksStatusPostResponses[keyof UpdateTasksStatusTasksStatusPostResponses];

export type CreateAnnotationAnnotationPostData = {
    body: AnnotationFullCreate;
    path?: never;
    query?: never;
    url: '/annotation';
};

export type CreateAnnotationAnnotationPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnnotationAnnotationPostError = CreateAnnotationAnnotationPostErrors[keyof CreateAnnotationAnnotationPostErrors];

export type CreateAnnotationAnnotationPostResponses = {
    /**
     * Successful Response
     */
    200: AnnotationDto;
};

export type CreateAnnotationAnnotationPostResponse = CreateAnnotationAnnotationPostResponses[keyof CreateAnnotationAnnotationPostResponses];

export type GetAnnotationsByIdAnnotationAnnotationIdGetData = {
    body?: never;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/annotation/{annotation_id}';
};

export type GetAnnotationsByIdAnnotationAnnotationIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnnotationsByIdAnnotationAnnotationIdGetError = GetAnnotationsByIdAnnotationAnnotationIdGetErrors[keyof GetAnnotationsByIdAnnotationAnnotationIdGetErrors];

export type GetAnnotationsByIdAnnotationAnnotationIdGetResponses = {
    /**
     * Successful Response
     */
    200: AnnotationDto;
};

export type GetAnnotationsByIdAnnotationAnnotationIdGetResponse = GetAnnotationsByIdAnnotationAnnotationIdGetResponses[keyof GetAnnotationsByIdAnnotationAnnotationIdGetResponses];

export type UpdateAnnotationResultAnnotationAnnotationIdPatchData = {
    /**
     * Result
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/annotation/{annotation_id}';
};

export type UpdateAnnotationResultAnnotationAnnotationIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnnotationResultAnnotationAnnotationIdPatchError = UpdateAnnotationResultAnnotationAnnotationIdPatchErrors[keyof UpdateAnnotationResultAnnotationAnnotationIdPatchErrors];

export type UpdateAnnotationResultAnnotationAnnotationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AnnotationDto;
};

export type UpdateAnnotationResultAnnotationAnnotationIdPatchResponse = UpdateAnnotationResultAnnotationAnnotationIdPatchResponses[keyof UpdateAnnotationResultAnnotationAnnotationIdPatchResponses];

export type GetAnnotationByTaskIdAnnotationsTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: number;
    };
    query?: {
        /**
         * User Email
         *
         * user_email
         */
        user_email?: string;
        /**
         * Direction of the annotation ('in' or 'out')
         */
        direction?: InOutEnum;
    };
    url: '/annotations/{task_id}';
};

export type GetAnnotationByTaskIdAnnotationsTaskIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnnotationByTaskIdAnnotationsTaskIdGetError = GetAnnotationByTaskIdAnnotationsTaskIdGetErrors[keyof GetAnnotationByTaskIdAnnotationsTaskIdGetErrors];

export type GetAnnotationByTaskIdAnnotationsTaskIdGetResponses = {
    /**
     * Response Get Annotation By Task Id Annotations  Task Id  Get
     *
     * Successful Response
     */
    200: Array<AnnotationDto>;
};

export type GetAnnotationByTaskIdAnnotationsTaskIdGetResponse = GetAnnotationByTaskIdAnnotationsTaskIdGetResponses[keyof GetAnnotationByTaskIdAnnotationsTaskIdGetResponses];

export type SkipAnnotationAnnotationSkipAnnotationIdPatchData = {
    body?: never;
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/annotation/skip/{annotation_id}';
};

export type SkipAnnotationAnnotationSkipAnnotationIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkipAnnotationAnnotationSkipAnnotationIdPatchError = SkipAnnotationAnnotationSkipAnnotationIdPatchErrors[keyof SkipAnnotationAnnotationSkipAnnotationIdPatchErrors];

export type SkipAnnotationAnnotationSkipAnnotationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AnnotationDto;
};

export type SkipAnnotationAnnotationSkipAnnotationIdPatchResponse = SkipAnnotationAnnotationSkipAnnotationIdPatchResponses[keyof SkipAnnotationAnnotationSkipAnnotationIdPatchResponses];

export type FinishAnnotationAnnotationFinishAnnotationIdPatchData = {
    /**
     * Result
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Annotation Id
         */
        annotation_id: number;
    };
    query?: never;
    url: '/annotation/finish/{annotation_id}';
};

export type FinishAnnotationAnnotationFinishAnnotationIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FinishAnnotationAnnotationFinishAnnotationIdPatchError = FinishAnnotationAnnotationFinishAnnotationIdPatchErrors[keyof FinishAnnotationAnnotationFinishAnnotationIdPatchErrors];

export type FinishAnnotationAnnotationFinishAnnotationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AnnotationDto;
};

export type FinishAnnotationAnnotationFinishAnnotationIdPatchResponse = FinishAnnotationAnnotationFinishAnnotationIdPatchResponses[keyof FinishAnnotationAnnotationFinishAnnotationIdPatchResponses];

export type GetAllAnnotationsAnnotationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * User Email
         *
         * user_email
         */
        user_email?: string;
        /**
         * annotation_status
         */
        status?: Status;
        /**
         * Project Id
         *
         * project id
         */
        project_id?: number;
        /**
         * Step Id
         *
         * step id
         */
        step_id?: number;
        /**
         * Start Created At
         *
         * start create date
         */
        start_created_at?: string;
        /**
         * End Created At
         *
         * end create date
         */
        end_created_at?: string;
        /**
         * Start Updated At
         *
         * start update date
         */
        start_updated_at?: string;
        /**
         * End Updated At
         *
         * end update date
         */
        end_updated_at?: string;
        /**
         * Start Validated At
         *
         * start validation date
         */
        start_validated_at?: string;
        /**
         * End Validated At
         *
         * end validation date
         */
        end_validated_at?: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/annotations';
};

export type GetAllAnnotationsAnnotationsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllAnnotationsAnnotationsGetError = GetAllAnnotationsAnnotationsGetErrors[keyof GetAllAnnotationsAnnotationsGetErrors];

export type GetAllAnnotationsAnnotationsGetResponses = {
    /**
     * Response Get All Annotations Annotations Get
     *
     * Successful Response
     */
    200: Array<AnnotationDto>;
};

export type GetAllAnnotationsAnnotationsGetResponse = GetAllAnnotationsAnnotationsGetResponses[keyof GetAllAnnotationsAnnotationsGetResponses];

export type GetTranscriptionTranscriptionGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Plugin Name
         */
        plugin_name?: string;
        /**
         * Transcription Format
         */
        transcription_format?: string;
        /**
         * Client Id
         */
        client_id?: string;
        /**
         * Channel
         */
        channel?: string;
        /**
         * Start Date
         */
        start_date?: string;
        /**
         * End Date
         */
        end_date?: string;
    };
    url: '/transcription';
};

export type GetTranscriptionTranscriptionGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTranscriptionTranscriptionGetError = GetTranscriptionTranscriptionGetErrors[keyof GetTranscriptionTranscriptionGetErrors];

export type GetTranscriptionTranscriptionGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteMediaMediaMediaIdDeleteData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/media/{media_id}';
};

export type DeleteMediaMediaMediaIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMediaMediaMediaIdDeleteError = DeleteMediaMediaMediaIdDeleteErrors[keyof DeleteMediaMediaMediaIdDeleteErrors];

export type DeleteMediaMediaMediaIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: MediaCreate;
};

export type DeleteMediaMediaMediaIdDeleteResponse = DeleteMediaMediaMediaIdDeleteResponses[keyof DeleteMediaMediaMediaIdDeleteResponses];

export type ReadMediaMediaMediaIdGetData = {
    body?: never;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/media/{media_id}';
};

export type ReadMediaMediaMediaIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMediaMediaMediaIdGetError = ReadMediaMediaMediaIdGetErrors[keyof ReadMediaMediaMediaIdGetErrors];

export type ReadMediaMediaMediaIdGetResponses = {
    /**
     * Successful Response
     */
    200: MediaDto;
};

export type ReadMediaMediaMediaIdGetResponse = ReadMediaMediaMediaIdGetResponses[keyof ReadMediaMediaMediaIdGetResponses];

export type UpdateDataMediaMediaMediaIdPatchData = {
    body: MediaCreate;
    path: {
        /**
         * Media Id
         */
        media_id: number;
    };
    query?: never;
    url: '/media/{media_id}';
};

export type UpdateDataMediaMediaMediaIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDataMediaMediaMediaIdPatchError = UpdateDataMediaMediaMediaIdPatchErrors[keyof UpdateDataMediaMediaMediaIdPatchErrors];

export type UpdateDataMediaMediaMediaIdPatchResponses = {
    /**
     * Successful Response
     */
    200: MediaDto;
};

export type UpdateDataMediaMediaMediaIdPatchResponse = UpdateDataMediaMediaMediaIdPatchResponses[keyof UpdateDataMediaMediaMediaIdPatchResponses];

export type CreateMediaMediaPostData = {
    body: MediaCreate;
    path?: never;
    query?: never;
    url: '/media';
};

export type CreateMediaMediaPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMediaMediaPostError = CreateMediaMediaPostErrors[keyof CreateMediaMediaPostErrors];

export type CreateMediaMediaPostResponses = {
    /**
     * Successful Response
     */
    200: MediaDto;
};

export type CreateMediaMediaPostResponse = CreateMediaMediaPostResponses[keyof CreateMediaMediaPostResponses];

export type ReadMediasMediasGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/medias';
};

export type ReadMediasMediasGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMediasMediasGetError = ReadMediasMediasGetErrors[keyof ReadMediasMediasGetErrors];

export type ReadMediasMediasGetResponses = {
    /**
     * Response Read Medias Medias Get
     *
     * Successful Response
     */
    200: Array<MediaDto>;
};

export type ReadMediasMediasGetResponse = ReadMediasMediasGetResponses[keyof ReadMediasMediasGetResponses];

export type SearchPluginsPluginsPluginIdSearchGetData = {
    body?: never;
    path: {
        /**
         * Plugin Id
         */
        plugin_id: number;
    };
    query: {
        /**
         * Query
         */
        query: string;
    };
    url: '/plugins/{plugin_id}/search';
};

export type SearchPluginsPluginsPluginIdSearchGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchPluginsPluginsPluginIdSearchGetError = SearchPluginsPluginsPluginIdSearchGetErrors[keyof SearchPluginsPluginsPluginIdSearchGetErrors];

export type SearchPluginsPluginsPluginIdSearchGetResponses = {
    /**
     * Response Search Plugins Plugins  Plugin Id  Search Get
     *
     * Successful Response
     */
    200: Array<PluginAutocompleteValueDto>;
};

export type SearchPluginsPluginsPluginIdSearchGetResponse = SearchPluginsPluginsPluginIdSearchGetResponses[keyof SearchPluginsPluginsPluginIdSearchGetResponses];

export type ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetData = {
    body?: never;
    path: {
        /**
         * Step Id
         */
        step_id: unknown;
        /**
         * Plugin Type
         */
        plugin_type: unknown;
        /**
         * Zone
         */
        zone: unknown;
    };
    query?: never;
    url: '/plugins/step/{step_id}/{plugin_type}/display/{zone}';
};

export type ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetError = ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetErrors[keyof ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetErrors];

export type ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetResponses = {
    /**
     * Response Read Plugins Plugins Step  Step Id   Plugin Type  Display  Zone  Get
     *
     * Successful Response
     */
    200: Array<PluginWithIdDto>;
};

export type ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetResponse = ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetResponses[keyof ReadPluginsPluginsStepStepIdPluginTypeDisplayZoneGetResponses];

export type ReadAllPluginsPluginsStepStepIdDisplayGetData = {
    body?: never;
    path: {
        /**
         * Step Id
         */
        step_id: number;
    };
    query: {
        /**
         * Zone
         */
        zone: Array<DisplayZone>;
    };
    url: '/plugins/step/{step_id}/display/';
};

export type ReadAllPluginsPluginsStepStepIdDisplayGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAllPluginsPluginsStepStepIdDisplayGetError = ReadAllPluginsPluginsStepStepIdDisplayGetErrors[keyof ReadAllPluginsPluginsStepStepIdDisplayGetErrors];

export type ReadAllPluginsPluginsStepStepIdDisplayGetResponses = {
    /**
     * Response Read All Plugins Plugins Step  Step Id  Display  Get
     *
     * Successful Response
     */
    200: Array<PluginWithIdDto>;
};

export type ReadAllPluginsPluginsStepStepIdDisplayGetResponse = ReadAllPluginsPluginsStepStepIdDisplayGetResponses[keyof ReadAllPluginsPluginsStepStepIdDisplayGetResponses];

export type CreatePluginPluginPostData = {
    body: PluginCreate;
    path?: never;
    query?: never;
    url: '/plugin';
};

export type CreatePluginPluginPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePluginPluginPostError = CreatePluginPluginPostErrors[keyof CreatePluginPluginPostErrors];

export type CreatePluginPluginPostResponses = {
    /**
     * Successful Response
     */
    200: PluginWithIdDto;
};

export type CreatePluginPluginPostResponse = CreatePluginPluginPostResponses[keyof CreatePluginPluginPostResponses];

export type DeletePluginPluginPluginIdDeleteData = {
    body?: never;
    path: {
        /**
         * Plugin Id
         */
        plugin_id: number;
    };
    query?: never;
    url: '/plugin/{plugin_id}';
};

export type DeletePluginPluginPluginIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePluginPluginPluginIdDeleteError = DeletePluginPluginPluginIdDeleteErrors[keyof DeletePluginPluginPluginIdDeleteErrors];

export type DeletePluginPluginPluginIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: PluginWithIdDto;
};

export type DeletePluginPluginPluginIdDeleteResponse = DeletePluginPluginPluginIdDeleteResponses[keyof DeletePluginPluginPluginIdDeleteResponses];

export type ReadPluginPluginPluginIdGetData = {
    body?: never;
    path: {
        /**
         * Plugin Id
         */
        plugin_id: number;
    };
    query?: never;
    url: '/plugin/{plugin_id}';
};

export type ReadPluginPluginPluginIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPluginPluginPluginIdGetError = ReadPluginPluginPluginIdGetErrors[keyof ReadPluginPluginPluginIdGetErrors];

export type ReadPluginPluginPluginIdGetResponses = {
    /**
     * Successful Response
     */
    200: PluginWithIdDto;
};

export type ReadPluginPluginPluginIdGetResponse = ReadPluginPluginPluginIdGetResponses[keyof ReadPluginPluginPluginIdGetResponses];

export type CreateStepStepPostData = {
    body: StepCreate;
    path?: never;
    query?: never;
    url: '/step';
};

export type CreateStepStepPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStepStepPostError = CreateStepStepPostErrors[keyof CreateStepStepPostErrors];

export type CreateStepStepPostResponses = {
    /**
     * Successful Response
     */
    200: StepCreate;
};

export type CreateStepStepPostResponse = CreateStepStepPostResponses[keyof CreateStepStepPostResponses];

export type ReadStepsStepsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/steps';
};

export type ReadStepsStepsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadStepsStepsGetError = ReadStepsStepsGetErrors[keyof ReadStepsStepsGetErrors];

export type ReadStepsStepsGetResponses = {
    /**
     * Response Read Steps Steps Get
     *
     * Successful Response
     */
    200: Array<StepDto>;
};

export type ReadStepsStepsGetResponse = ReadStepsStepsGetResponses[keyof ReadStepsStepsGetResponses];

export type DeleteTagTagTagKeyDeleteData = {
    body?: never;
    path: {
        /**
         * Tag Key
         */
        tag_key: string;
    };
    query?: never;
    url: '/tag/{tag_key}';
};

export type DeleteTagTagTagKeyDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTagTagTagKeyDeleteError = DeleteTagTagTagKeyDeleteErrors[keyof DeleteTagTagTagKeyDeleteErrors];

export type DeleteTagTagTagKeyDeleteResponses = {
    /**
     * Successful Response
     */
    200: TagCreate;
};

export type DeleteTagTagTagKeyDeleteResponse = DeleteTagTagTagKeyDeleteResponses[keyof DeleteTagTagTagKeyDeleteResponses];

export type ReadTagTagTagKeyGetData = {
    body?: never;
    path: {
        /**
         * Tag Key
         */
        tag_key: string;
    };
    query?: never;
    url: '/tag/{tag_key}';
};

export type ReadTagTagTagKeyGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTagTagTagKeyGetError = ReadTagTagTagKeyGetErrors[keyof ReadTagTagTagKeyGetErrors];

export type ReadTagTagTagKeyGetResponses = {
    /**
     * Successful Response
     */
    200: TagDto;
};

export type ReadTagTagTagKeyGetResponse = ReadTagTagTagKeyGetResponses[keyof ReadTagTagTagKeyGetResponses];

export type UpdateTagTagTagKeyPatchData = {
    body: TagDto;
    path: {
        /**
         * Tag Key
         */
        tag_key: string;
    };
    query?: never;
    url: '/tag/{tag_key}';
};

export type UpdateTagTagTagKeyPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTagTagTagKeyPatchError = UpdateTagTagTagKeyPatchErrors[keyof UpdateTagTagTagKeyPatchErrors];

export type UpdateTagTagTagKeyPatchResponses = {
    /**
     * Successful Response
     */
    200: TagDto;
};

export type UpdateTagTagTagKeyPatchResponse = UpdateTagTagTagKeyPatchResponses[keyof UpdateTagTagTagKeyPatchResponses];

export type CreateTagTagPostData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/tag';
};

export type CreateTagTagPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTagTagPostError = CreateTagTagPostErrors[keyof CreateTagTagPostErrors];

export type CreateTagTagPostResponses = {
    /**
     * Successful Response
     */
    200: TagCreate;
};

export type CreateTagTagPostResponse = CreateTagTagPostResponses[keyof CreateTagTagPostResponses];

export type ReadTagsTagsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/tags';
};

export type ReadTagsTagsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTagsTagsGetError = ReadTagsTagsGetErrors[keyof ReadTagsTagsGetErrors];

export type ReadTagsTagsGetResponses = {
    /**
     * Response Read Tags Tags Get
     *
     * Successful Response
     */
    200: Array<TagDto>;
};

export type ReadTagsTagsGetResponse = ReadTagsTagsGetResponses[keyof ReadTagsTagsGetResponses];

export type ReadTaskCommentTaskCommentTaskCommentIdGetData = {
    body?: never;
    path: {
        /**
         * Task Comment Id
         */
        task_comment_id: number;
    };
    query?: never;
    url: '/task_comment/{task_comment_id}';
};

export type ReadTaskCommentTaskCommentTaskCommentIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskCommentTaskCommentTaskCommentIdGetError = ReadTaskCommentTaskCommentTaskCommentIdGetErrors[keyof ReadTaskCommentTaskCommentTaskCommentIdGetErrors];

export type ReadTaskCommentTaskCommentTaskCommentIdGetResponses = {
    /**
     * Successful Response
     */
    200: TaskCommentDto;
};

export type ReadTaskCommentTaskCommentTaskCommentIdGetResponse = ReadTaskCommentTaskCommentTaskCommentIdGetResponses[keyof ReadTaskCommentTaskCommentTaskCommentIdGetResponses];

export type ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetData = {
    body?: never;
    path: {
        /**
         * Task Comment Task Id
         */
        task_comment_task_id: number;
    };
    query?: never;
    url: '/taskComments/{task_comment_task_id}';
};

export type ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetError = ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetErrors[keyof ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetErrors];

export type ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetResponses = {
    /**
     * Response Read Task Comments By Task Id Taskcomments  Task Comment Task Id  Get
     *
     * Successful Response
     */
    200: Array<TaskCommentDto>;
};

export type ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetResponse = ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetResponses[keyof ReadTaskCommentsByTaskIdTaskCommentsTaskCommentTaskIdGetResponses];

export type CreateTaskCommentTaskCommentPostData = {
    body: TaskCommentCreate;
    path?: never;
    query?: never;
    url: '/taskComment';
};

export type CreateTaskCommentTaskCommentPostErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskCommentTaskCommentPostError = CreateTaskCommentTaskCommentPostErrors[keyof CreateTaskCommentTaskCommentPostErrors];

export type CreateTaskCommentTaskCommentPostResponses = {
    /**
     * Successful Response
     */
    200: TaskCommentCreate;
};

export type CreateTaskCommentTaskCommentPostResponse = CreateTaskCommentTaskCommentPostResponses[keyof CreateTaskCommentTaskCommentPostResponses];

export type DeleteTaskCommentTaskCommentTaskCommentIdDeleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Task Comment Id
         */
        task_comment_id: number;
    };
    url: '/taskComment/{taskComment_id}';
};

export type DeleteTaskCommentTaskCommentTaskCommentIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskCommentTaskCommentTaskCommentIdDeleteError = DeleteTaskCommentTaskCommentTaskCommentIdDeleteErrors[keyof DeleteTaskCommentTaskCommentTaskCommentIdDeleteErrors];

export type DeleteTaskCommentTaskCommentTaskCommentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: TaskCommentCreate;
};

export type DeleteTaskCommentTaskCommentTaskCommentIdDeleteResponse = DeleteTaskCommentTaskCommentTaskCommentIdDeleteResponses[keyof DeleteTaskCommentTaskCommentTaskCommentIdDeleteResponses];

export type UpdateTaskCommentTaskCommentTaskCommentIdPatchData = {
    body: TaskCommentDto;
    path?: never;
    query: {
        /**
         * Task Comment Id
         */
        task_comment_id: number;
    };
    url: '/taskComment/{taskComment_id}';
};

export type UpdateTaskCommentTaskCommentTaskCommentIdPatchErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTaskCommentTaskCommentTaskCommentIdPatchError = UpdateTaskCommentTaskCommentTaskCommentIdPatchErrors[keyof UpdateTaskCommentTaskCommentTaskCommentIdPatchErrors];

export type UpdateTaskCommentTaskCommentTaskCommentIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TaskCommentDto;
};

export type UpdateTaskCommentTaskCommentTaskCommentIdPatchResponse = UpdateTaskCommentTaskCommentTaskCommentIdPatchResponses[keyof UpdateTaskCommentTaskCommentTaskCommentIdPatchResponses];

export type ReadTaskCommentsTaskCommentsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/taskComments';
};

export type ReadTaskCommentsTaskCommentsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskCommentsTaskCommentsGetError = ReadTaskCommentsTaskCommentsGetErrors[keyof ReadTaskCommentsTaskCommentsGetErrors];

export type ReadTaskCommentsTaskCommentsGetResponses = {
    /**
     * Response Read Task Comments Taskcomments Get
     *
     * Successful Response
     */
    200: Array<TaskCommentDto>;
};

export type ReadTaskCommentsTaskCommentsGetResponse = ReadTaskCommentsTaskCommentsGetResponses[keyof ReadTaskCommentsTaskCommentsGetResponses];

export type GetHealthManagementHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/management/health';
};

export type GetHealthManagementHealthGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
};

export type GetHealthManagementHealthGetError = GetHealthManagementHealthGetErrors[keyof GetHealthManagementHealthGetErrors];

export type GetHealthManagementHealthGetResponses = {
    /**
     * Return HTTP Status Code 200 (OK)
     */
    200: HealthCheck;
};

export type GetHealthManagementHealthGetResponse = GetHealthManagementHealthGetResponses[keyof GetHealthManagementHealthGetResponses];

export type GetHealthMetricsManagementMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/management/metrics';
};

export type GetHealthMetricsManagementMetricsGetErrors = {
    /**
     * Unauthorized
     */
    401: ExceptionResponse;
    /**
     * Forbidden
     */
    403: ExceptionResponse;
};

export type GetHealthMetricsManagementMetricsGetError = GetHealthMetricsManagementMetricsGetErrors[keyof GetHealthMetricsManagementMetricsGetErrors];

export type GetHealthMetricsManagementMetricsGetResponses = {
    /**
     * Prometheus metrics in plain text format.
     */
    200: unknown;
};
